version: "3"
 
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp" # dns
      - "53:53/udp" # dns
      - "800:80/tcp" # interface web
    environment:
      TZ: 'Europe/Paris'
      WEBPASSWORD: 'password' # mot de passe de l'interface web
    volumes:
      - '/srv/docker/pihole/etc-pihole:/etc/pihole/'
      - '/srv/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d/'
 
    restart: unless-stopped